name: Workflow event triggers
on:
  workflow_dispatch:
#  push:
#  schedule:
#    - cron: "*/15 * * * *" # every 15 minutes

jobs:
  show-the-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: show_trigger
        run: echo "This workflow was triggered by a ${{ github.event_name }} event."