name: Building React App
on:
  workflow_dispatch:

jobs:
  inspect-directory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-third-party-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Inspect app
        run: ls -lt react-app
