#==============================================================================
# This workflow uses a third-party actions to build a React App.
#
# Notice we use the `working-directry` command to avoid unecessary CDing.
#==============================================================================
name: Third party actions
on:
  workflow_dispatch:

jobs:
  inspect-directory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-third-party-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Inspect app
        run: ls -lt react-app
