#==============================================================================
# This workflow uses a third-party actions to build a React App.
#
# Notice we use the `working-directry` command to avoid unecessary CDing.
#==============================================================================
name: Third party actions
on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-third-party-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
