name: Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode'
        type: boolean
        default: false
jobs:
  workflow-run-context:
    runs-on: ubuntu-latest
    steps:
      - name: Display workflow run context information
        run: | 
          echo "Event name: ${{ github.event_name }}"
          echo "Branch reference:" ${{ github.head_ref }}
          echo "SHA:" ${{ github.sha }}
          echo "Actor:" ${{ github.actor }}
          echo "Workflow:" ${{ github.workflow }}
          echo "Run ID:" ${{ github.run_id }}
          echo "Run number:" ${{ github.run_number }}
  repository-context:
    runs-on: ubuntu-latest
    steps:
      - name: Display repository context information
        run: | 
          echo "Repository variable: ${{ vars.REPOSITORY_VAR }}"
