name: Working with variables
on:
  workflow_dispatch:
env:
  MY_ENV_VAR: "workflow"
jobs:

  print-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable using context form
        run: | 
          echo "Environment variable: ${{ env.MY_ENV_VAR }}"
      - name: Print environment variable using implicit form
        run: | 
          echo "Environment variable: $MY_ENV_VAR"

  print-repo-var:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository variable using context form
        run: | 
          echo "Repository variable: ${{ vars.REPOSITORY_VAR }}"
      - name: Print repository variable using implicit form
        run: | 
          echo "Repository variable: REPOSITORY_VAR"