name: Control flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: Should the "unit tests" job pass # set this to false to cause the unit test job to fail
        required: true
        default: false
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: echo "Linting code"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: |
          if ${{ github.event.inputs.pass-unit-tests }}; then
            echo "Unit tests passed"
          else
            echo "Unit tests failed"
            exit 1
          fi

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: [lint-build, unit-tests]
    steps:
      - name: Deploy to non-prod
        run: echo "Deploying to non-prod"