name: Job outputs
on:
  workflow_dispatch:

jobs:
  produce-output:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.build.outputs.env_token }}
      domain: ${{ steps.build.outputs.env_domain }}
    steps:
    - name: build job's output
      id: build
      run: |
        echo "env_token=production" >> "$GITHUB_OUTPUT"
        echo "env_domain=example.com" >> "$GITHUB_OUTPUT"

  consume-output:
    needs: produce-output
    runs-on: ubuntu-latest
    steps:
      - name: echo previous job's token output
        run: echo ${{ needs.produce-output.outputs.token }}
      - name: echo previous job's domain output
        run: echo ${{ needs.produce-output.outputs.domain }}
