name: Matrix fundamentals

on:
  workflow_dispatch:

jobs:
  backwards-compatability:
    name: "Check compatability for ${{ matrix.os }} with Node version ${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os : [ubuntu-latest, windows-latest]
        version: [18, 19, 20]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Run tests
        run: echo "Running tests on OS=${{ matrix.os }} with Node version=${{ matrix.version }}"
